apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - port: 3307 # The port that the service is running on in the cluster
      targetPort: 3307 # The port exposed by the service

---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mysql-deploy
  labels:
    app: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0 # Image that will be used inside the container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3307 # The port that the container is running on in the cluster
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: achieversoft