server:
  servlet:
    contextPath: /ecommapp/customerdata

spring:
  application:
    name: customerdata
  datasource:
    url: jdbc:mysql://localhost:3306/achieversoft
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none





